[package]
name = "cupid_parse"
version = "0.1.0"
edition = "2021"



[dependencies]
cupid_lex = { version = "0.1.0", path = '../cupid-lex' }
cupid_util = { version = "0.1.0", path = '../cupid-util' }
serde = { version = "1.0", features = ["derive"] }