[package]
name = "cupid-ast"
version = "0.1.0"
edition = "2021"


[dependencies]
derive_more = "0.99.17"
serde = { version = "1.0", features = ["derive"] }

cupid-lex = { path = '../cupid-lex' }
cupid-util = { path = '../cupid-util' }