[package]
name = "cupid-env"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
cupid-ast = { path = '../cupid-ast' }
cupid-lex = { path = '../cupid-lex' }
cupid-util = { path = '../cupid-util' }
