[package]
name = "cupid_passes"
version = "0.1.0"
edition = "2021"

[dependencies]
cupid_semantics = { path = '../cupid-semantics' }
cupid_types = { path = '../cupid-types' }
cupid_util = { path = '../cupid-util' }
