[package]
name = "cupid_passes"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
auto-implement = { path = '../auto-implement' }
cupid_types = { path = '../cupid-types' }
cupid_util = { path = '../cupid-util' }
trace = { path = '../trace' }
