[package]
name = "cupid_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
cupid_lex = { path = '../cupid-lex' }
cupid_ast = { path = '../cupid-ast' }
cupid_util = { path = '../cupid-util' }
cupid_trace = { path = '../cupid-trace' }