[workspace]

members = [
	"cupid-analysis",
	"cupid-ast",
	"cupid-lex",
	"cupid-parse",
	"cupid-trace",
	"cupid-util"
]

[package]
name = "cupid"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
clap = { version = "3.1.18", features = ["derive"] }

cupid_util = { path = 'cupid-util' }
cupid_lex = { path = 'cupid-lex' }
cupid_parse = { path = 'cupid-parse' }
cupid_ast = { path = 'cupid-ast' }
cupid_analysis = { path = 'cupid-analysis' }
cupid_trace = { path = 'cupid-trace' }