[package]
name = "cupid"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
	"cupid-analysis",
	"cupid-ast",
	"cupid-builder",
	"cupid-lex",
	"cupid-parse",
	"cupid-passes",
	"cupid-scope",
	"cupid-semantics",
	"cupid-trace",
	"cupid-types",
	"cupid-util"
]

[dependencies]
colored = "2.0.0"
clap = { version = "3.1.18", features = ["derive"] }

cupid_analysis = { path = 'cupid-analysis' }
cupid_ast = { path = 'cupid-ast' }
cupid_builder = { path = 'cupid-builder' }
cupid_debug = { path = 'cupid-debug' }
cupid_lex = { path = 'cupid-lex' }
cupid_parse = { path = 'cupid-parse' }
cupid_passes = { path = 'cupid-passes' }
cupid_scope = { path = 'cupid-scope' }
cupid_semantics = { path = 'cupid-semantics' }
cupid_trace = { path = 'cupid-trace' }
cupid_types = { path = 'cupid-types' }
cupid_util = { path = 'cupid-util' }