[package]
name = "cupid"
version = "0.1.0"

[workspace]
members = []

[dependencies]
mimalloc = { version = "*", default-features = false }

[dev-dependencies]
regex = "1.5.4"
test-generator = "0.3.0"