[package]
name = "cupid"
version = "0.1.0"

[workspace]
members = [
    "cupid-fmt"
]

[dependencies]
mimalloc = { version = "*", default-features = false }
cupid-fmt = { path = "cupid-fmt" }
serde = "1.0.155"

[dev-dependencies]
regex = "1.5.4"
test-generator = "0.3.0"
