[package]
name = "cupid"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
colored = "2.0.0"
clap = { version = "3.1.9", features = ["derive"] }
wasm-bindgen = "0.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"
harness = false