brace_style = "PreferSameLine"
chain_width = 80
wrap_comments = true
fn_call_width = 80
format_code_in_doc_comments = true
format_macro_matchers = true
overflow_delimited_expr = true
imports_granularity = "Crate"
reorder_impl_items = true
group_imports = "StdExternalCrate"
trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true
imports_layout = "Vertical"