[package]
name = "cupid_scope"
version = "0.1.0"
edition = "2021"

[dependencies]
cupid_ast = { path = '../cupid-ast' }
cupid_debug = { path = '../cupid-debug' }
cupid_lex = { path = '../cupid-lex' }
cupid_trace = { path = '../cupid-trace' }
cupid_util = { path = '../cupid-util' }