[package]
name = "cupid_debug"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
cupid_ast = { path = '../cupid-ast' }
cupid_lex = { path = '../cupid-lex' }
cupid_trace = { path = '../cupid-trace' }
cupid_util = { path = '../cupid-util' }