[package]
name = "cupid_parse"
version = "0.1.0"
edition = "2021"

[dependencies]
cupid_lex = { path = '../cupid-lex' }
cupid_passes = { path = '../cupid-passes' }
cupid_util = { path = '../cupid-util' }