[package]
name = "cupid-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
cupid-lex = { path = '../cupid-lex' }
cupid-ast = { path = '../cupid-ast' }
cupid-env = { path = '../cupid-env' }
cupid-util = { path = '../cupid-util' }
trace = { path = '../trace' }